### ISSUE TITLE
cifar10 data

### ISSUE THREAD

**Issue by thiti-s** [lchamon/csl#1]
Hi,
Thanks for the package and note on the code. I am trying to learn from it. I tried to walk through "robustness" application but I do not have the data, cifar-10.

It was noted in the datasets.py in csl.datasets that 

    You can download the dataset in PyTorch tensor format from
    https://www.seas.upenn.edu/~luizf/data/cifar-10.zip

However, the link is already expired. Can you suggest how can I obtain the data?

Thanks,
Mai

**Comment by thiti-s** [comment]
I already got it. Thanks.

**Comment by lfochamon** [comment]
Sorry @tsuttaket, for some reason I don't get notified when someone posts an issue here!

I've updated the link to my new domain. Thanks for letting me know!
